### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by NicksonYap** [owsas/parse-offline#20]
Hi, 
Found ur repo and seems interesting.

But there doesn't seem to be a guide on using this package.

Mind giving some examples?

Thanks!

**Comment by NicksonYap** [comment]
This package worked really well.

Managed to use it by referring to the test scripts.

Thankd a lot!

**Comment by jcguarinpenaranda** [comment]
Hello!

I am very glad that you found it useful. However I apologize for not having
docs in the README.

You may send us a pull request if you want :) It would be great!


Juan Camilo Guarín Peñaranda
Ingeniero Multimedia
Otherwise SAS | http://owsas.com
<http://mailstat.us/tr/t/pleg6bmaikkbgvuq/h/http://owsas.com/>

2018-05-01 16:52 GMT-05:00 Nickson Yap <notifications@github.com>:

**Comment by orolle** [comment]
Hi Juan,
thanks for this piece of software :+1: 
I am new to parse framework and have no idea how to glue parse and parse-offline together.
A small hello world example with code walk through would be nice :-)

**Comment by jcguarinpenaranda** [comment]
Hello Oliver,

Sorry for the late response. Today I added some documentation, please check it out :)
